### ISSUE TITLE
How to know when PR is missing commits from master.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/test-infra#116]
In cases where new commits are merged into master the PR might fall behind so when we want to test the PR against master need to know when these have diverged and need to rebase etc.

**Comment by geekodour** [comment]
@krasi-georgiev now that we have amGithubNotifier, think we can have a bash script checking for new commits in the PR and manually trigger a alert through amGithubNotifier for this. what do you think?

**Comment by krasi-georgiev** [comment]
I was thinking maybe when a test is triggered to check the status of the PR and if it is behind master just post an additional comment on GH. If possible best to keep it simple and not involve the `amGithubNotifier`
