### ISSUE TITLE
lets use the promtool to replace the python querier.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/test-infra#125]
lets build a docker image that uses the promtool to send queries to the tested Prometheus servers

**Comment by krasi-georgiev** [comment]
[This is the Python querier](https://github.com/prometheus/prombench/tree/master/cmd/load-generator) that we want to replace with the [Promtool](https://github.com/prometheus/prometheus/tree/master/cmd/promtool)

and [here is the manifest](https://github.com/prometheus/prombench/blob/master/components/prombench/manifests/benchmark/6_loadgen.yaml) how it is deployed

**Comment by gouthamve** [comment]
Hmm, just curious. The Python querier also exposes metrics about the query
latencies. How do you propose to do that using just promtool?

Further if we're going to build a wrapper around promtool for it, we're
better off with the Python querier no?

Thanks
Goutham

**Comment by geekodour** [comment]
metrics in the python querier:
```
1 - loadgen_query_duration_seconds
2 - loadgen_queries_total
3 - loadgen_failed_queries_total
```
I am not very happy with what I thought of but was thinking about starting with replacing L116 with async subprocess call to promtool. 

- `loadgen_queries_total` it's just a increment every time promtool is called
-  `loadgen_failed_queries_total` can be set using return codes, if we need more granularity on return codes we can change how promtool behaves.
- `loadgen_query_duration_seconds` just calculate this once the async process finishes.

https://github.com/prometheus/prombench/blob/93113c77da24f189ff58139e4df01f1cfebd4b9e/cmd/load-generator/main.py#L116-L129

If we don't want to use subprocess, I assume we can write a go implementation and import the promtool package but that will be using the HTTP API anyway.

What do you suggest?

cc @gouthamve

**Comment by geekodour** [comment]
Or we could extract `querier` out as a separate tool like scalar and also expose the /metrics endpoint from there.

Where are the `loadgen_*` metrics used? grepping the metrics just shows the declarations and the grafana dashboard provisioning does not seem to be using them either.

**Comment by krasi-georgiev** [comment]
I looked at the promtool code quickly and @gouthamve 	 is right using the promtool wouldn't make any sense here. 
It seems that re-implementing the python querier in golang is the way to go.

The main benefit for this is that most Prom devs are already familiar with golang so can contribute easily.

**Comment by geekodour** [comment]
Yes, that'd be a better approach. I'll follow that.
