### ISSUE TITLE
Extend Prombench for scalability tests

### ISSUE THREAD

**Issue by sipian** [prometheus/test-infra#128]
At promcon, people were interested in knowing on how to use prombench for scalability tests for their Prometheus infrastructures.

**Comment by bwplotka** [comment]
Revisiting old bugs... 

So prombench is focused on Prometheus development, where we simulate real world scenarios. This means this issue could go to other place (e.g. mailing list/prometheus discussion) for wider feedback. I believe it's out of scope for this project.

For your own load testing / scalability testing of Prometheus setups, you might need to tailor it to your architecture (daemonset? single replica? hashmod? prometheus operator enhanced? agent mode? special Prom features?). 

However there are definitely things one could reuse like:
* https://github.com/prometheus-community/avalanche for metric generation 
* query load generator https://github.com/prometheus/test-infra/tree/master/tools/load-generator
* Prometheus or [potential remote write receiver tester](https://github.com/prometheus/test-infra/issues/766)
