### ISSUE TITLE
Repository has no MAINTAINERS.md file

### ISSUE THREAD

**Issue by beorn7** [prometheus/test-infra#151]
But https://github.com/prometheus/prombench/blob/master/CONTRIBUTING.md refers to it (and every prometheus/... repo should have one anyway).

@krasi-georgiev are you the current (de-facto) maintainer?

**Comment by krasi-georgiev** [comment]
I think would be best to link the contributing file to the official Prometheus one to avoid maintaining 2 files.

> @krasi-georgiev are you the current (de-facto) maintainer?

Harsh and I did the work so far and I got involved only because I thought it is crucial to have something like this in place, but wouldn't want to be long term maintainer.

**Comment by gouthamve** [comment]
Contributing file sometimes differs from repo to repo, as it could have custom instructions. Like for example instructions to test the comments prombench makes on PRs. Or maybe the issue labelling is different for both repos, and you could guide new contributors to the relevant `easy-issue` labels.

Even if there is nothing different, I'd argue to keep it different as it would link to a different `MAINTAINERS.md` file.

**Comment by sipian** [comment]
A separate file will also be helpful in informing new contributors whom to contact on IRC / other media , if one is willing to contribute.

**Comment by krasi-georgiev** [comment]
PR is welcome :)

**Comment by bwplotka** [comment]
Fixed now https://github.com/prometheus/test-infra/blob/master/MAINTAINERS.md
