### ISSUE TITLE
check if Prow can be replaced with GitHub Actions

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/test-infra#167]
https://github.com/features/actions

Currently we use Prow and need to maintain a fork with a custom Prombench plugin. 
https://github.com/prometheus/test-infra

If we can use Github actions instead will remove another thing we need to maintain.

**Comment by krasi-georgiev** [comment]
just found out that Prow now supports external plugins so in this case can use unmodified Prow with just the Prombench external plugin
https://github.com/kubernetes/test-infra/blob/8304ccbbacab0c97bcf689f1147c16939d5d0405/prow/plugins/README.md#external-plugins

**Comment by geekodour** [comment]
@krasi-georgiev continuing work on #31 as it requires some changes to the test-infra, do you think working on this one (making `benchmark` an external plugin and adding other changes) before #31  would be a good idea? (from #174 )

changes like, updating the test-infra repo, removing extra components(we're only using prow of all), updating the README to be more specific to prombench's test-infra (the current one still has what the fork comes with by default), fixing `deck` (command page, plugin page not working etc)

**Comment by krasi-georgiev** [comment]
Yeah lets check if we can use github actions first.
We should have it enabled for https://github.com/prometheus-community soon and I will add you there so you start experimenting.
