### ISSUE TITLE
Compared versions are not queried at the same rate.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/test-infra#173]
It was pointed to me by @free that when we run the tests both versions don't get the same query load which leads to misleading comparison.

Here is the proof:
http://prombench.prometheus.io/prometheus-meta/graph?g0.range_input=7h&g0.end_input=2018-10-19%2016%3A02&g0.step_input=60&g0.expr=rate(prometheus_engine_query_duration_seconds_count%7Bjob%3D%22prometheus%22%2Cslice%3D%22inner_eval%22%2Cnamespace%3D%22prombench-4763%22%2Cprometheus%3D~%22(test%2B).*%22%7D%5B1h%5D)&g0.tab=0

http://prombench.prometheus.io/prometheus-meta/graph?g0.range_input=7h&g0.end_input=2018-10-19%2016%3A02&g0.step_input=60&g0.expr=rate(prometheus_engine_query_duration_seconds_count%7Bjob%3D%22prometheus%22%2Cslice%3D%22inner_eval%22%2Cnamespace%3D%22prombench-4763%22%2Cprometheus%3D%22test-master%22%7D%5B1h%5D)%20%2F%20on%20(job%2C%20slice%2C%20namespace)%0Arate(prometheus_engine_query_duration_seconds_count%7Bjob%3D%22prometheus%22%2Cslice%3D%22inner_eval%22%2Cnamespace%3D%22prombench-4763%22%2Cprometheus%3D%22test-pr-4763%22%7D%5B1h%5D)&g0.tab=0

**Comment by geekodour** [comment]
@krasi-georgiev was working on the golang querier. the links in this issue no longer seem to show the desired results, any idea why this might be happening (that the compared versions are not queried at the same rate). ?

**Comment by krasi-georgiev** [comment]
No I am sorry it has to be investigate. I don't know what could be the reason.

With some tweaking you should be able to run the same query for some more recent Prombench test to check the difference.

**Comment by geekodour** [comment]
Okay I'll investigate this one. As I was looking at the Dockerfiles for both the prometheus versions are run in different environments. prometheus-builder runs on top of the go11 image which seems to use alpine and the official prometheus releases seem to be using busybox(a custom one). Not sure if it's of any significance to this issue.

I think it would be a good idea to run both in the same environment.

**Comment by krasi-georgiev** [comment]
yeah I believe the problem is somewhere else. Did you manage to fix that query from the original comment, that should give you a better clue on where is the problem.

**Comment by free** [comment]
If I had to guess (and with no clue of what the code is doing) I'd say it was simply a result of the fact that the slower a query runs on one build, the longer it takes to issue the next query. I.e. as long as whatever is running the queries doesn't follow a fixed schedule (e.g. issue one query every 50 ms) you will never get comparable results.

One easy way around this would be to simply use recording rules and let Prometheus deal with when to run the queries. All you would have to look at afterwards would be how many evaluations were skipped (if any) and (assuming that wasn't the case) compare the CPU load/memory utilization.

**Comment by krasi-georgiev** [comment]
@free thanks for the feedback that is really useful!

**Comment by geekodour** [comment]
I'll try to reproduce this today.

If this is the case,
>  the fact that the slower a query runs on one build, the longer it takes to issue the next query

won't having recording rules have the same issue? as the recording rules will be run independently, the build that is taking longer to process a query still will, no?

> with no clue of what the code is doing

the currently prometheus instances are started at slightly different times (can be fixed after #180) and the current querier waits for a specified amount of time before starting to send queries. I'll also try to time the current querier and look into the metrics produced by it.

related maybe: https://github.com/prometheus/prometheus/issues/5307
