### ISSUE TITLE
kubectl does not show all deployments from gke

### ISSUE THREAD

**Issue by geekodour** [prometheus/test-infra#181]
This issue is not directly related to prombech but not sure about why it's behaving this way.

got the credentials using 

```shell
$ gcloud container clusters get-credentials $CLUSTER_NAME --zone=$ZONE --project=$PROJECT_ID
```

deployments are shown in the UI
[![][1]][1]

[1]: https://i.stack.imgur.com/dH25K.png

When I do `kubectl get deployments` to get all deployments using kubectl, 

it shows: 

```bash
λ  prombench (restarter) × kubectl get deployments                                                                                                                                              
NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE                                                                                                                              
grafana-core      1         1         1            1           36m                                                                                                                             
prometheus-meta   1         1         1            1           35m
```
Seems like it's showing the deployments done in the `prow` node but not from the other nodes.

cc @sipian @krasi-georgiev  any idea why is this happening?

**Comment by krasi-georgiev** [comment]
I think you need to select all namespaces.

**Comment by krasi-georgiev** [comment]
anyway for issues like this it is best to ask in the k8s channels or ping me or @sipian 	directly if we can give some pointers. 

Don't think we need to keep this one open. Feel free to ping me on IRC  if you can't figure it out and will try to give some more ideas.
