### ISSUE TITLE
Running prometheus-builder as an init container

### ISSUE THREAD

**Issue by geekodour** [prometheus/test-infra#183]
I have a suggestion related to `prometheus-builder`, 

`prometheus-builder` would be more fit for an [init Container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/).

That way prometheus-builder would work as follows:
- build the PR version
- copy the binary and supporting files to a mounted volume (pref. [emptyDir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir))
- end of prometheus-builder init container

Then in the actual container for the pod, we can use the base image that the release is using and mount the volume where we copied over the binary and supporting files and execute the prometheus binary from there using kubernetes `commands` and `args` much like what happens with the release image.

as mentioned in #173

**Comment by krasi-georgiev** [comment]
yep that sound like a good idea, just go for it.

Don't think we need to have an issue for that. just open the PR and will discuss there.
