### ISSUE TITLE
[suggestion] new directory structure

### ISSUE THREAD

**Issue by geekodour** [prometheus/test-infra#190]
The k8s manifest files for deploying prombench and prow are kind of mixed together currently. This issue suggests a better directory structure which separates the manifest files accordingly.

This will also be convinient when migrating away from prow to github actions or moving to a newer prow version,

suggested structure is as follows( only changes are shown) :
- `/temp` -> `/images`
- `/components` -> `/manifests`
```
.
├── ...
├── images
│   └── prometheus-builder
├── ...
├── manifests
    ├── clusterwide
    ├── cluster.yaml
    ├── prombench
    └── prow
```

inside `/manifests`:
- `/components/prow/manifests/rbac.yaml` -> `/manifests/clusterwide/rbac/1_gcloud_role_binding.yaml`
- `/components/prombench/manifests/results` -> `/manifests/clusterwide/rbac/2_prometheus_role_binding.yaml`
```
.
├── clusterwide
│   ├── nginx-controller.yaml
│   ├── rbac
│   │   ├── 1_gcloud_role_binding.yaml
│   │   └── 2_prometheus_role_binding.yaml
│   └── results
│       ├── grafana_dashboard_provision.yaml
│       ├── grafana_dashboard_prow_bench.yaml
│       ├── grafana_dashboard_prow_node.yaml
│       ├── grafana_datasource.yaml
│       ├── grafana_deployment.yaml
│       ├── node-exporter.yaml
│       └── prometheus-meta.yaml
├── cluster.yaml
├── prombench
│   ├── benchmark
│   │   ├── 1a_namespace.yaml
│   │   ├── 1b_serviceaccount.yaml
│   │   ├── 1c_cluster-role-binding.yaml
│   │   ├── 2_fake-webserver.yaml
│   │   ├── 3_prometheus-test.yaml
│   │   ├── 4_node-exporter.yaml
│   │   ├── 5_nginx-ingress-routes.yaml
│   │   └── 6_loadgen.yaml
│   └── nodepools.yaml
└── prow
    ├── prow_internals_1.yaml
    ├── prow_internals_2.yaml
    └── secrets.yaml
```

the `/manifest/prombench` directory now only contains files that need to be deployed each new benchmark test.

If we decide to make these changes we'll need to update the changes in other places aswell.

**Comment by krasi-georgiev** [comment]
ok, please make a PR and make sure you update the README.md and test a full deployment from scratch to make sure that following the README.md will results a fully functional Prombench setup.

About the `/temp` It was my idea to keep is as temp as a reminder that we want to move away from the custom builder and use either promu or add this as part of the CI somehow.

P.S.
this is a good source how to structure golang projects.
https://github.com/golang-standards/project-layout
