### ISSUE TITLE
Update load generator to use a env var for domain name

### ISSUE THREAD

**Issue by geekodour** [prometheus/test-infra#202]
the load-generator utility which works as the `querier` uses hardcoded strings for the domain name. 

Eg.
https://github.com/prometheus/prombench/blob/5bf056cfa3c97550ff4680abc8bcf73c6f7ba9bd/cmd/load-generator/main.py#L46

We can change this to use a env var or something similar, but there was a previous discussion for converting this into a golang tool (https://github.com/prometheus/prombench/issues/125) where I did some work locally. 

@krasi-georgiev how should we address this? should we improve the python tool or work on the golang tool?

**Comment by krasi-georgiev** [comment]
Don't have any python devs that would maintain it so lets convert to a golang tool. 
This is not a priority so lets leave it for after closing the High priority issues first.
