### ISSUE TITLE
 Storing secrets in GitHub Actions

### ISSUE THREAD

**Issue by geekodour** [prometheus/test-infra#209]
When moving to GitHub actions, it will be good to keep this in mind if it does not move out of Beta by the time we implement it.

> Note: GitHub Actions is currently available in public beta, which means you should avoid using it for high-value workflows and content during this beta period.

also
> Warning: Do not store production secrets in the API during the limited public beta period. Production workflows should not be used during the limited public beta.

more info:
https://developer.github.com/actions/managing-workflows/storing-secrets/

**Comment by geekodour** [comment]
think this can be closed now as GithubActions is GA now.

**Comment by krasi-georgiev** [comment]
yep
