### ISSUE TITLE
circleci tests not running

### ISSUE THREAD

**Issue by geekodour** [prometheus/test-infra#215]
`.circleci/config.yml` was added in https://github.com/prometheus/prombench/pull/213 but tests don't seem to be running on new PRs. prombench is enabled in circleci as @krasi-georgiev stated.

more info: https://circleci.com/docs/2.0/enable-checks/#github-checks-waiting-for-status-in-github

cc @SuperQ  @simonpasquier

**Comment by simonpasquier** [comment]
I believe it should be fixed now (see https://github.com/prometheus/prombench/pull/216 which also reuses the new Circle CI orb). The last missing bit was to enable the CI for pull requests from forks.
You'd need to update your open PRs to trigger the CI again.
