### ISSUE TITLE
Update Dockerfile and image for prombench

### ISSUE THREAD

**Issue by geekodour** [prometheus/test-infra#223]
In addition to some changes done recently, another change that is needed in the `prombench` `Dockerfile` is that `Makefile` now includes `Makefile.common` which uses the `go` binary. 

https://github.com/prometheus/prombench/blob/7d2e3503af0ea3f47561d4b5c6f4837973146f3e/Makefile#L3

https://github.com/prometheus/prombench/blob/7d2e3503af0ea3f47561d4b5c6f4837973146f3e/Makefile.common#L35

So we probably need to add a base image that has the go binary in it, otherwise install go in the current base image inside the `Dockerfile`. 

[Current Dockerfile](https://github.com/prometheus/prombench/blob/master/cmd/prombench/Dockerfile) also do not contain `Makefile.common` which breaks `make` but not having `go` installed in the base image just prints warnings and does not break `make`

**Comment by krasi-georgiev** [comment]
which target requires the go binary?

Also the current Dockerfile looks quite bad. We need to use multistage build to build prombench at one stage and just use the binary in another.

Not even sure why we need these:
https://github.com/prometheus/prombench/blob/7d2e3503af0ea3f47561d4b5c6f4837973146f3e/cmd/prombench/Dockerfile#L8-L10
