### ISSUE TITLE
Enable named files for arguments in commentMonitor

### ISSUE THREAD

**Issue by geekodour** [prometheus/test-infra#250]
Currently when using commentMonitor we're getting the `PR_NUMBER` as such:
`export PR_NUMBER=$(cat /github/home/ARG_1);,`

I think it will be better to have the filename of known args as their env var names, think this can be implemented in `writeArgs` by checking the value of `data` to a  list of known regex for the envvars and when it's not in the list of known regex we can add it the name `ARG_X` and so on.
https://github.com/prometheus/prombench/blob/156828803d0c72fbe024dccd7804a702ec1cf23f/cmd/tools/commentMonitor/main.go#L133

So that we can do something like:
`export PR_NUMBER=$(cat /github/home/PR_NUMBER);,`

**Comment by krasi-georgiev** [comment]
yep ,very good idea!
