### ISSUE TITLE
Prombench failing due to yarn dependency missing from Prometheus builder

### ISSUE THREAD

**Issue by csmarchbanks** [prometheus/test-infra#299]
Prombench is not able to start up the Prometheus instances for testing pull requests due to the yarn dependency missing. Logs:
```
2019-10-28T17:53:26.058914493Z >> Creating prometheus binaries
2019-10-28T17:53:26.173078238Z cd web/ui/react-app && yarn --frozen-lockfile
2019-10-28T17:53:26.173809471Z /bin/sh: 1: yarn: not found
2019-10-28T17:53:26.173922738Z Makefile:35: recipe for target 'web/ui/react-app/node_modules' failed
```
cc: @krasi-georgiev and @geekodour 
also @juliusv

**Comment by juliusv** [comment]
Seems like one would have to add https://github.com/prometheus/golang-builder/blob/2eedfc17ad288369f306bb87b6a9de75eac2c6e2/1.13/base/Dockerfile#L16-L19

...to https://github.com/prometheus/prombench/blob/master/prombench/temp/prometheus-builder/Dockerfile

**Comment by geekodour** [comment]
The new Dockerfile adds few env vars :

https://github.com/prometheus/prombench/blob/f03a0d26e4874b794ef56989920857c60c1cf991/prombench/temp/prometheus-builder/build.sh#L5

`GITHUB_ORG` and `GITHUB_REPO`

Which are not set in the currently running prombench manifest setup, pushing this will break the use of `prometheus-builder:2.0.1`

@krasi-georgiev should the use of this env vars be removed and then publish this image with the modifications that @juliusv suggested? or we can wait for the till #298 is merged, then will be able to run this in the new setup.

#298 should be done today.

**Comment by krasi-georgiev** [comment]
@geekodour I would say go to the commit before this breaking change and apply the fix there to push the new image also open a PR to create a 2.0 branch. Additional also open a PR against the latest version as well.

**Comment by geekodour** [comment]
Added and pushed the changes to the dockertag `prometheus-builder:2.0.1`

@csmarchbanks  `/benchmark` should work now.

**Comment by krasi-georgiev** [comment]
create prombench v2.0.0 branch so can open a PR against that one as well
https://github.com/prometheus/prombench/tree/v2.0.0

**Comment by geekodour** [comment]
@krasi-georgiev this can be closed now?

**Comment by krasi-georgiev** [comment]
yep, thanks
