### ISSUE TITLE
Allow running prombench locally

### ISSUE THREAD

**Issue by geekodour** [prometheus/test-infra#333]
Currently prombench development requires the user to setup GKE environment. Having prombench to run in a local k8s cluster would make adding changes much easier and faster. Support for kubeconfig and a proper way to switch local and GKE environment is not available yet. Adding these features will be essential to the completion of the project.

This most probably will require adding a local provider to https://github.com/prometheus/test-infra/tree/master/pkg/provider

Since prombench runs in multiple nodes, we can explore [k8s/kind](https://github.com/kubernetes-sigs/kind) but open to other suggestions for this.

related #341

**Comment by imrajdas** [comment]
Hi @geekodour , I would like to take this issue as part of GSOC 2020.

**Comment by harkishen** [comment]
Hi @rajdas98 , sorry but I am already working on this. Can you take some other issue?

**Comment by geekodour** [comment]
Hello @rajdas98 @Harkishen-Singh 
current provider code lives in https://github.com/prometheus/test-infra/tree/master/pkg/provide

@rajdas98  did you start working on it? you can also join riot channel at https://prometheus.io/community/ and ping me in it for any questions.

**Comment by rajdas98** [comment]
Hi @Harkishen-Singh . It's good to know that you have started working on this issue. 
Actually I am also working with this issue. Let's have a good PR for this issue.

**Comment by rajdas98** [comment]
Thanks, @geekodour . I already joined the slack channel. Based on the status of the issue, I have designed it to work with the KIND cluster having a standard host path, also exploring KubeADM. Will send a proposal on it after the 16th of March.

**Comment by geekodour** [comment]
@rajdas98 @Harkishen-Singh since the student submission period has started, feel free to send me your proposals for review. :)

**Comment by siddharthlal25** [comment]
Hi @geekodour, has this issue been taken up as GSoC 2020 project? if not I am quite eager to learn and contribute.

**Comment by geekodour** [comment]
sorry! @siddharthlal25 task is assigned for to be worked during the GSoC period. Please feel free to pickup any other issue :)

**Comment by bwplotka** [comment]
Looks like it was fixed in https://github.com/prometheus/test-infra/pull/390
