### ISSUE TITLE
Allow running prombench on EKS

### ISSUE THREAD

**Issue by geekodour** [prometheus/test-infra#341]
Currently, prombench runs on GKE. It'll be good to have it run on [EKS](https://aws.amazon.com/eks/) as well. If we need to migrate away from GKE, that'll be super useful.

provider code live here: https://github.com/prometheus/test-infra/tree/master/pkg/provider

related #333 (about running prombench locally)

**Comment by bwplotka** [comment]
I believe this is possible, but it's not tested on CI/we don't run it anywhere.

https://github.com/prometheus/test-infra/blob/master/prombench/manifests/cluster_eks.yaml
