### ISSUE TITLE
Add additional rules or  queries to catch regression

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/test-infra#345]
To catch cases like these regressions.

https://github.com/prometheus/prometheus/issues/7048
https://github.com/prometheus/prometheus/issues/6968

cc @bwplotka

**Comment by bwplotka** [comment]
I think we need micro benchmarks instead, but this will help as well :+1:

**Comment by krasi-georgiev** [comment]
yep, adding more queries to measure latencies is always good!
