### ISSUE TITLE
Prombench is built from master on every push so no need to clone the repo dinamically.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/test-infra#357]
Now that the CI builds and pushed all images on every push to master don't need the clone script https://github.com/prometheus/test-infra/blob/master/prombench/cmd/prombench/clone.sh

Can also remove the need for https://github.com/prometheus/test-infra/blob/master/Makefile , because the docker context can be inside the folder for each tool.

**Comment by geekodour** [comment]
> Can also remove the need for https://github.com/prometheus/test-infra/blob/master/Makefile , because the docker context can be inside the folder for each tool.

We can probably remove the docker part, it will also be good to review the `make docker` references in the README files. We'll still need the `all` target for circle ci tests I guess?
