### ISSUE TITLE
Need to upgrade client-go version

### ISSUE THREAD

**Issue by imrajdas** [prometheus/test-infra#371]
- For the implementation of kind provider https://github.com/prometheus/test-infra/issues/333, client-go v1.11.0 is not supported.
- Upgrading client-go will also affect the k8s provider.
  - Currently, client-go(v1.11.0) functions didn't take the `context` parameter,  Need to pass a empty context parameter `context.TODO()`
    Ex- https://github.com/prometheus/test-infra/blob/master/pkg/provider/k8s/k8s.go#L256

**Comment by imrajdas** [comment]
cc @geekodour

**Comment by geekodour** [comment]
closed by #372
