### ISSUE TITLE
Differentiate between commit hash id or branch name or tag name in funcbench

### ISSUE THREAD

**Issue by nevill** [prometheus/test-infra#380]
Commit hash is always hexadecimal, in rare case it can be [meaningful words](https://en.wikipedia.org/wiki/Hexspeak), conflicting with branch or tag names.
We need to tell user using full length(20 byte) hash id as input to avoid the confusion.
In this case, new checks has to be added to funcbench.

Reference:
* https://github.com/prometheus/test-infra/pull/377#pullrequestreview-425746785

**Comment by geekodour** [comment]
Closed by #377
