### ISSUE TITLE
[comment-monitor] - use cli flags instead of env vars and auto generate the readme.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/test-infra#382]
I think in the past we used env vars because we were running it in GH actions, but this caused big delays to post comments so now that it runs 24/7 can use cli args instead of env variables. 
In the same or a different PR can add to autogenerate the readme from the cliflags

Should also cleanup anything related to GH actions like the eventmap file for examples

**Comment by geekodour** [comment]
closed by #378
