### ISSUE TITLE
Add funcbench logs to Github comment

### ISSUE THREAD

**Issue by geekodour** [prometheus/test-infra#385]
Funcbench logs can only be seen in GKE stackdriver before the funcbench Job is deleted. It'll be nice to have these logs posted as part of the result or error comment posted back to Github.

**Comment by roidelapluie** [comment]
Or in Loki

**Comment by bwplotka** [comment]
FYI: We decided to remove `funcbench` for now from this repo, so this is no longer relevant. Thanks!
