### ISSUE TITLE
[funcbench] allow running package wide benchmarks.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/test-infra#396]
Make something like this possible in funcbnech

```go test -benchmem -run=^$ github.com/prometheus/prometheus/promql -bench .```

**Comment by geekodour** [comment]
When running funcbench `github.com/prometheus/prometheus/` this part is already part of the `--owner` and `--repo` flags, so just the package name could work? something like this:

```
λ go test -mod vendor -run ^$ -bench "^BenchmarkIsolationWithState.*$" -benchmem -benchtime 1s -timeout 2h0m0s ./tsdb
goos: linux
goarch: amd64
pkg: github.com/prometheus/prometheus/tsdb
BenchmarkIsolationWithState/10-8                  360586              3568 ns/op             177 B/op          3 allocs/op
BenchmarkIsolationWithState/100-8                  43920             27403 ns/op            1034 B/op          5 allocs/op
BenchmarkIsolationWithState/1000-8                  5451            460433 ns/op          103539 B/op         96 allocs/op
BenchmarkIsolationWithState/10000-8                  504           5299230 ns/op          499344 B/op        704 allocs/op
PASS
ok      github.com/prometheus/prometheus/tsdb   8.244s
```

what do you think?

**Comment by nevill** [comment]
Yes, we mainly talk about funcbench syntax here. 
It should work like `./funcbench master Benchmark.* ./promql`.
In case you don't specify any package name, it can fallback to `./funcbench master Benchmark.*`, even `./funcbench master .*`

**Comment by krasi-georgiev** [comment]
The shortest form looks the most intuitive as well I think

`/funcbench master ./promql`

**Comment by nevill** [comment]
The form `/funcbench master ./promql` has conflict with `/funcbench master .*`.
I think `/funcbench <branch or tag or commit hash> <regexp> [package name]` can represent the syntax.

**Comment by krasi-georgiev** [comment]
can you give a few examples of how would that look like?

**Comment by nevill** [comment]
These are currently supported:
- /funcbench master .*
- /funcbench master BechmarkName.*
- /funcbench v2.16 .*
- /funcbench v2.16 BechmarkName.*
- /funcbench 00aabbccddee .*
- /funcbench 00aabbccddee Benchmark.*

The following will be added:
- /funcbench master Benchmark.* ./promql
- /funcbench v2.16 Benchmark.* ./promql
- /funcbench 112233aabbcc Benchmark.* ./promql

**Comment by nevill** [comment]
Actually, we may omit ./ for package names.
e.g instead of `/funcbench master Benchmark.* ./promql`, we do `/funcbench master Benchmark.* promql`

**Comment by krasi-georgiev** [comment]
lets keep it as close as possible to the golang syntacts so if possible lets have the package name first.

/funcbench master ./promql Benchmark.*

**Comment by geekodour** [comment]
Currently the package name is added to the end, so I think `/funcbench master Benchmark.* ./promql` will be closer to the actual go test command we're running? and if unspecified we just use `./...` 
```
go test -mod vendor -run ^$ -bench ^BenchmarkIsolation.*$ -benchmem -benchtime 1s -timeout 2h0m0s ./...
go test -mod vendor -run ^$ -bench ^BenchmarkIsolation.*$ -benchmem -benchtime 1s -timeout 2h0m0s ./tsdb
```

**Comment by krasi-georgiev** [comment]
actually both work so yeah that would be easier to implement.
