### ISSUE TITLE
[funcbench] for comments with incorrect syntacs post back a comment with examples

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/test-infra#397]
at the moment when I post a /funcbench comment with incorrect syntax it just replies with a comment that the syntax is incorrect. It would be a better experience to post back all available formats that are accepted.

**Comment by geekodour** [comment]
This is posted back by the comment-monitor, it can post back the regex that it expects to be matched to but posting the available formats will need changing comment-monitor. should we just return the expected regex for now?

**Comment by nevill** [comment]
I think this issue should be fixed in comment monitor instead of funcbench, prombench can also be affected by this.

**Comment by krasi-georgiev** [comment]
how about having 

comment_template_success: .....
comment_template_failure: .....

the comment_template_failure needs to be auto-generated so that it doesn't diverge from the funbench cli and we should also have a test for this. Check that the generated examples match exactly what funcbench expects..

**Comment by geekodour** [comment]
closed by #403
