### ISSUE TITLE
[funcbench] when a comment doesn't match any tests should also post a comment

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/test-infra#398]
At the moment if I post `/funcbench master TestDoesntExist` There is no feedback that this test doesn't exist. It would be useful to post a comment like: `Test expression ... didn't match any existing tests. Available command formats....`

**Comment by nevill** [comment]
@krasi-georgiev This one is also can be closed since #400 gets merged.

**Comment by krasi-georgiev** [comment]
thanks, in the future can use the PR keywords to close issues from PRs when merged. https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#:~:text=issue%20will%20close.-,Closing%20an%20issue%20in%20the%20same%20repository,merged%20into%20the%20default%20branch.

**Comment by nevill** [comment]
Yes I see. In fact I did it in the commit message [there](https://github.com/nevill/test-infra/commit/dd7601e81bd21a73ce37408d41f3bfc128751052), but seems it's squashed and gone away.

**Comment by geekodour** [comment]
Closed by #400
