### ISSUE TITLE
[funcbench] Improvments on reducing conflicts

### ISSUE THREAD

**Issue by nevill** [prometheus/test-infra#401]
- Prefix GitHub org/repo name and in cluster name and namespace. This can avoid potential conflicts when testing a forked project.
- Test if a previous instance is running for the same PR. If there is, abort the newly created workflow.

**Comment by nox1134** [comment]
Hi @geekodour! I'd like to work on this issue. Could you please assign it to me? How do I get started?

**Comment by bwplotka** [comment]
FYI: We decided to remove `funcbench` for now from this repo, so this is no longer relevant. Thanks!
