### ISSUE TITLE
Funcbench is not cleaning its resources

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/test-infra#414]
12:30:07 gke.go:151: Couldn't parse deployment files: couldn't apply template to file 
                         manifests/benchmark/2_secrets.yaml: Failed to execute parse file err: template: resource:8:13: executing 
                         "resource" at <.GITHUB_TOKEN>: map has no entry for key "GITHUB_TOKEN"

seen in https://github.com/prometheus/prometheus/runs/889809405?check_suite_focus=true

**Comment by geekodour** [comment]
Happening after merging https://github.com/prometheus/test-infra/pull/392 ~(think forgot to update github workflow on prometheu/prometheus)~
