### ISSUE TITLE
Add perflock to funcbench

### ISSUE THREAD

**Issue by bwplotka** [prometheus/test-infra#429]
This ensures better safety in terms of CPU results - useful for shared environments.

Would be nice to do it programmatically: https://github.com/aclements/perflock/issues/6

**Comment by geekodour** [comment]
Yes this would be super nice I think! Let's see what aclements has to say.

Also, I am just unsure about how this would behave in containerized environments. Currently funcbench runs on a k8s pod in the main k8s node itself. Any suggestions?

I think it was tried running directly on a GCP VM but the results were more or less the same.
@krasi-georgiev @nevill  would have more info on this.

**Comment by bwplotka** [comment]
Well the thing is that this is literally global locking mechanism allowing to run more than one benchmark at the time (: 
Useful when w have one VM! 

I am not sure how it works in a containerized environment though (:

**Comment by krasi-georgiev** [comment]
Yes lets try it!

**Comment by bwplotka** [comment]
funcbench was removed from the project, for now.
