### ISSUE TITLE
Prombench is not running anymore

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/test-infra#444]
Hello

http://prombench.prometheus.io/hook returns 503. Can someone please have a look?

**Comment by geekodour** [comment]
Hi @roidelapluie I'll take a look at this, it seems like there needs to make other changes after the `master` to `main` migration. It seems like there was a PR to change this: https://github.com/prometheus/test-infra/pull/443 but it'll need more changes, i'll comment.

**Comment by roidelapluie** [comment]
thanks

**Comment by geekodour** [comment]
This is fixed now. Looking into the changes needed for the `master` to `main` migration or the changes in https://github.com/prometheus/test-infra/pull/443 will suffice. :)
