### ISSUE TITLE
Upgrade Prometheus Meta version

### ISSUE THREAD

**Issue by LeviHarrison** [prometheus/test-infra#455]
The current version of Prometheus Meta specified in the manifest is `v2.20.0`, which is pretty old itself, but the instance actually running is even older, `v2.10.0`.

https://github.com/prometheus/test-infra/blob/bec88220803fd49ac8f007d3ff72d707d6a69a3c/prombench/manifests/cluster-infra/3b_prometheus-meta.yaml#L204

http://prombench.prometheus.io/prometheus-meta/status

**Comment by bwplotka** [comment]
Fixed in https://github.com/prometheus/test-infra/pull/463
