### ISSUE TITLE
Load-generator main.py Missing argument for Yaml.load

### ISSUE THREAD

**Issue by Zanabazer** [prometheus/test-infra#530]
The file tools/load-generator/main.py uses the yaml.load function at line 121.

`    config = yaml.load(open("/etc/loadgen/config.yaml", 'r').read())`

This is failing the loadgen-querier resources when deploying the benchmark in a Docker Kuberenetes deployment method. The function yaml.load from the PyYaml package was upgraded to require a second argument dictating the Loader type in PyYaml 5.4. The current version of PyYaml in the repo is 6.0. 

Line 121 of  tools/load-generator/main.py should be updated to
`config = yaml.load(open("/etc/loadgen/config.yaml", 'r').read(), Loader=yaml.FullLoader)`

**Comment by bboreham** [comment]
Looks like this is where the breaking change came in: https://github.com/yaml/pyyaml/commit/c2743653bc89e42679ba097b4f9888db47c61d63

This repo updated to PyYAML 6.0 in #525, so I guess we are missing a CI check that this still works.

**Comment by Zanabazer** [comment]
Looks to be fixed with commit 860e8e6
