### ISSUE TITLE
Replace fake webserver with Avalanche

### ISSUE THREAD

**Issue by saketjajoo** [prometheus/test-infra#559]
Currently, the setup uses fake webserver as the metrics emitter which only [supports standard metrics](https://github.com/prometheus/test-infra/blob/master/tools/fake-webserver/main.go#L61-L71) (e.g. the `debug/*` metrics and the `process` and `go` metrics). Having variable/configurable metrics would help collect good benchmarking data. Hence, I suggest replacing the fake webserver component with [avalanche](https://github.com/prometheus-community/avalanche).

Avalanche [provides several configurable options](https://github.com/prometheus-community/avalanche/blob/main/cmd/avalanche.go#L33-L51) to change the configurations (e.g. metrics count, label count, series count, metric name length, etc.). Although, this may not represent production-like metrics (for e.g. metric names are like `avalanche_metric_mmmmm_01` does not look like a real workload metric), having different configurations can help collect good data to benchmark and analyze the Prometheus's performance.

---

Sample / Reference Commit: https://github.com/saketjajoo/test-infra/commit/eb8678bdfa2f5404bbf3997103f20cfb18ca6877

**Comment by bwplotka** [comment]
This is still relevant, especially after the latest changes in 0.6.0 https://github.com/prometheus-community/avalanche/pull/101

**Comment by bwplotka** [comment]
Did a quick [research](https://docs.google.com/document/d/17XxO5kuLpwEqjuV9qpoK-Rj7scqjcw8dY3NUuAcha2w/edit?tab=t.0) around swapping fake-webserver with avalanche.

I think I would propose we keep fake-webserver. We could simplify it a bit and move to avalanche project as another mode to improve maintainability.

WDYT @ArthurSens @bboreham @kakkoyun 

Closing for now, we can reopen.

**Comment by ArthurSens** [comment]
I think we'll need avalanche to Benchmark CTs, but agree this can be done in a custom benchmark

**Comment by bwplotka** [comment]
We can (and should) add [native histograms](https://github.com/prometheus/test-infra/issues/594) and CTs to fake-webserver IMO (pull the latest client and configure nhs)
