### ISSUE TITLE
Current state of the prometheus/test-infra

### ISSUE THREAD

**Issue by geekodour** [prometheus/test-infra#593]
Apologies for being away from the project, was away from software development and open source in general for a while but getting back at things now. 

Saw a lot of nice updates in recent months to the repo from @saketjajoo and @bwplotka :) .  How is prometheus/prometheus using the test-infra now? did we move from GCP to AWS?

What is the current direction of the repo?

cc: @bwplotka @saketjajoo @roidelapluie

**Comment by bwplotka** [comment]
Wow! Thanks for being here!

 Wanna jump on #prometheus-dev or so on Slack channel to talk?

Generally we would love:

* Better load generation https://github.com/prometheus/test-infra/issues/629
* Generating native histogram load https://github.com/prometheus/test-infra/issues/594
* Parca improvements https://github.com/prometheus/test-infra/issues/630
* And probably the most important -- remote write benchmark: https://github.com/prometheus/test-infra/issues/249 -- for this it would epic to think about exercising agent mode too e.g. via prombench flag or so.

Probably more in the issues (: Let us know how we can help for you to have more time for it (e.g. mentorship etc are potential option).

Not sure what about other stuff in this repo. E.g funcbench, I think we don't use it, but in Thanos we do have something similar, with simple scripts https://github.com/thanos-io/promql-engine/blob/main/.github/workflows/benchmark.yaml 

From other exciting stuff my team in Google now use prombench too (!). We have our [fork](https://github.com/GoogleCloudPlatform/prometheus-test-infra) as we had to use Cloud Build vs GH Action (secret compliance) and we focus our tests on exporting data not querying, but we reuse and depend on a lot, allowing us to help here from time to time (:  We also killed commentMonitor service as you can do it via CI job these days.

**Comment by bwplotka** [comment]
Next time, I think it might be better to ask this on Slack e.g. started new channel `#prombench-dev` https://cloud-native.slack.com/archives/C07TT6DTQ02
