### ISSUE TITLE
Rewrite load-generator in Go

### ISSUE THREAD

**Issue by SuperQ** [prometheus/test-infra#688]
The `/tools/load-generator` is the only component of this repo that is in Python. It would be nice to replace this with a Go binary in order to eliminate the Python ecosystem dependency for one tool. There are also no CI tests for this Python code, so we don't know if it's broken when Python or other requirements change.

**Comment by Vandit1604** [comment]
I would like to pick this up.

**Comment by HarshitNagpal29** [comment]
@SuperQ PTAL https://github.com/prometheus/test-infra/pull/725

**Comment by Vandit1604** [comment]
Thanks, @HarshitNagpal29, for the PR. I was also working on this, but my changes are identical to yours, so it's fine.
Please ask in future if somebody is working on an issue to minimize wasted effort.

Other than that, the PR looks good. Thanks again.

**Comment by HarshitNagpal29** [comment]
> Thanks, @HarshitNagpal29, for the PR. I was also working on this, but my changes are identical to yours, so it's fine.
> Please ask in future if somebody is working on an issue to minimize wasted effort.
> 
> Other than that, the PR looks good. Thanks again.

I am really sorry for not asking first, I thought you might not be working on it as it was assigned earlier but again completely my fault I should have communicated with you, will take care of this in future.

**Comment by SuperQ** [comment]
@Vandit1604 If you don't open a PR, nobody knows you're working on it. :smile:

**Comment by Vandit1604** [comment]
Apologies, I didn't know that.

**Comment by SuperQ** [comment]
Feel free to submit your own solution. The current one does not pass tests.

**Comment by Vandit1604** [comment]
I checked and found out that `http://prombench.prometheus.io/14515/prometheus-pr` is not found and is causing the querier to fail, with more than 30 `404 status code` is returned. I'll investigate the manifest files to see if there's some issue in nginx-ingress configurations.

**Comment by SuperQ** [comment]
Fixed in #748

**Comment by bwplotka** [comment]
I believe https://github.com/prometheus/test-infra/issues/688#issuecomment-2365227765 closed it.
