### ISSUE TITLE
When a prombench apply commands fails display the last error

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/test-infra#72]
At the moment we retry few times to verify if the deployment is up, but after so many retries we give up.
It would be better to display the deployment error why it failed so that we don't have to look at the gke console all the time.

**Comment by sipian** [comment]
In the [struct DeploymentStatus ](https://godoc.org/k8s.io/api/apps/v1#DeploymentStatus) in k8s API there is no proper field stating reason of error.
On displaying all the elements of the struct I get

`2018/08/05 12:55:37 error applying 'components/prombench/manifests/benchmark/4_node-exporter.yaml' err:Request for 'applying deployment:node-exporter-prometheus-test-master' hasn't completed after retrying 10 times. Status : &DeploymentStatus{ObservedGeneration:1,Replicas:1,UpdatedReplicas:1,AvailableReplicas:0,UnavailableReplicas:1,Conditions:[{Available False 2018-08-05 12:53:22 +0530 IST 2018-08-05 12:53:22 +0530 IST MinimumReplicasUnavailable Deployment does not have minimum availability.} {Progressing True 2018-08-05 12:53:22 +0530 IST 2018-08-05 12:53:22 +0530 IST ReplicaSetUpdated ReplicaSet "node-exporter-prometheus-test-master-5cdcff8597" is progressing.}],ReadyReplicas:0,CollisionCount:nil,}`


when the actual reason as seen from `kubectl describe` is 

`Warning  FailedScheduling  1m (x7 over 1m)  default-scheduler  0/4 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 2 node(s) didn't match node selector, 2 node(s) didn't match pod affinity rules, 2 node(s) didn't match pod affinity/anti-affinity.`

I don't think much information can be obtained from the first message.
