### ISSUE TITLE
annotation "kubernetes.io/ingress.class" is deprecated,  use 'spec.ingressClassName' instead

### ISSUE THREAD

**Issue by yomek33** [prometheus/test-infra#720]
The annotation `kubernetes.io/ingress.class` is deprecated and generates a warning in Kubernetes logs. The current configuration should be updated to use the `spec.ingressClassName` field instead.
https://github.com/prometheus/test-infra/blob/34a189da3778d9035d430e3213f5c9dd18d520a7/prombench/manifests/cluster-infra/3b_prometheus-meta.yaml#L260
https://github.com/prometheus/test-infra/blob/34a189da3778d9035d430e3213f5c9dd18d520a7/prombench/manifests/cluster-infra/7b_commentmonitor_deployment.yaml#L73
It may appear in other parts of yaml files.

FYI: More details about this deprecation and changes can be found in 
https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#deprecating-the-ingress-class-annotation

**Comment by kushalShukla-web** [comment]
do I need to remove from other files ?

**Comment by bwplotka** [comment]
Fixed in https://github.com/prometheus/test-infra/pull/726

**Comment by bboreham** [comment]
Apparently making this change broke everything.
Maybe some other change was needed?

**Comment by bboreham** [comment]
Should it be a _field_ in the spec object, and not an annotation?

**Comment by bwplotka** [comment]
Ups, sorry, didn't actually apply to check... my fault

**Comment by bboreham** [comment]
Should be fixed by #770
