### ISSUE TITLE
Remove Loki  (or fix the compactor crashloop)

### ISSUE THREAD

**Issue by bwplotka** [prometheus/test-infra#780]
Compactor is crashlooping for Loki

<img width="1752" alt="image" src="https://github.com/user-attachments/assets/b1c9df35-0dfc-47ec-ac86-26aa3b143e7d">

Seems like a configuration issue, but I wonder if we are using Loki for Prombench use cases. We run in GKE and logging is already OOTB in, so it feels we could save some cost by removing Loki for our use case:

<img width="2030" alt="image" src="https://github.com/user-attachments/assets/453fac89-2462-4100-977c-c6a60cd55bd5">

Disclaimer: I am working for Google Cloud, proposing to remove Grafana Loki instance from prombench, so second opinion from non-Googler Prometheus team member would be nice here (((((: 

cc @bboreham @kakkoyun are you using Loki?

**Comment by bboreham** [comment]
I fixed up the config.  https://github.com/prometheus/test-infra/pull/781

I find Google Cloud logging terrible to use compared to Loki.
Maybe it's a case of what you are used to.

E.g. it decorates everything with an angry red mark
<img width="850" alt="image" src="https://github.com/user-attachments/assets/15cc75b0-616b-469e-a2c0-501e1381c5f6">

**Comment by bboreham** [comment]
More generally, the `test-infra` repo is set up to be usable in different situations - GCP, AWS, Kind.
It would simplify quite a few things if we hard-coded to work only at Google.

**Comment by bwplotka** [comment]
> E.g. it decorates everything with an angry red mark

Fixable (e.g. switching to json fixes it), but I get the experience preference! Will do later.

> More generally, the test-infra repo is set up to be usable in different situations - GCP, AWS, Kind.
It would simplify quite a few things if we hard-coded to work only at Google.

Agree, let's add an issue (:

**Comment by bwplotka** [comment]
Added https://github.com/prometheus/test-infra/issues/791

**Comment by bwplotka** [comment]
Sounds like there's sentiment to keep Loki, so closing this for now.
